[build]
  command = "npm run build"
  publish = "dist"
  base = "."

# Evita que Netlify intente incluir Sanity
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[ignore]]
  paths = ["galeria-cuadros/*"]

# Redirección para SPA (Vite/Vue Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
